apiVersion: apps/v1
kind: Deployment
metadata:
  name: weblancehub-deployment
  namespace: weblancehub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weblancehub
  template:
    metadata:
      labels:
        app: weblancehub
    spec:
      containers:
        - name: weblancehub
          image: 867809929056.dkr.ecr.us-east-1.amazonaws.com/weblancehub:latest
          ports:
            - containerPort: 80
