apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcart-deployment
  namespace: petcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petcart
  template:
    metadata:
      labels:
        app: petcart
    spec:
      containers:
        - name: petcart
          image: 867809929056.dkr.ecr.us-east-1.amazonaws.com/petcart:latest
          ports:
            - containerPort: 80
